### PR TITLE
All time filter

### PR DESCRIPTION
**Pull request by ShubhamVerma1811**
Hey @mikecao ,
This PR is for the issue #554.

I have added the All Time filter to the dropdown by adding a new field in the filterOptions of DateFilter.
Also fixed the imports.
Please go through the code and let me know if there are any changes that are required, I would like to look into them.

Thank you.

### CODE REVIEW

**Comment by mikecao** [comment]
@ShubhamVerma1811 since we already have the website id, we can query for the `createdAt` when the user selects the `All Time` option.

**Comment by ShubhamVerma1811** [comment]
Got it.
Will look into this approach.

**Comment by ShubhamVerma1811** [comment]
Hey @mikecao , Sorry I have not been been able to work on this PR for a while.
I have noticed there are #882  and a101d639d396d5a784cf2d4ce36bf879b1c52ce6 with better approaches.
In that case this PR can be closed.

**Comment by mikecao** [comment]
Done in v1.25.0

**Pull request closed without merging**
