### PR TITLE
✨ Added Tamil Language Support

### PR DESCRIPTION
**Pull request by mcnaveen**

### CODE REVIEW

**Review by mikecao — CHANGES_REQUESTED** [review]
Thank you!

Just one issue with this line:
`"message.active-users": "{x} தற்போதைய {x, பார்வையாளர்கள், ஒன்று {visitor} மற்ற {visitors}}"`

You need to translate the visitor/visitors if you have plural forms in your language, like this:
`"message.active-users": "{x} nuværende {x, plural, one {bruger} other {brugere}}"`

**Comment by mcnaveen** [comment]
@mikecao Exactly where this line will show inside umami? And I can't see Tamil in Language Switcher.

**Comment by mikecao** [comment]
@mcnaveen You need to run `build-lang` to get the language to show up

**Comment by mcnaveen** [comment]
```
ninja@softinttech:~/Scripts/umami$ build-lang
build-lang: command not found
```

What I'm doing wrong?

**Comment by mikecao** [comment]
`npm run build-lang`

**Comment by mikecao** [comment]
@mcnaveen If you can't figure it out that's fine. I'll just merge to my dev branch and make the changes. You can update the translation later.

**Pull request merged**
