### PR TITLE
disable telemetry of yarn and next by default

### PR DESCRIPTION
**Pull request by tim-hub**
I personally prefer disabling telemetry by default.

What do you guys think about it? Is it a good idea for you?

@mikecao @hugomd

### CODE REVIEW

**Comment by hugomd** [comment]
Out of interest, why do you prefer disabling telemetry?

I'm fine with the change, I really don't mind. Is there a way to make this change at the project level, so it affects users who aren't deploying with Docker?

**Comment by tim-hub** [comment]
> Out of interest, why do you prefer disabling telemetry?
> 
> I'm fine with the change, I really don't mind. Is there a way to make this change at the project level, so it affects users who aren't deploying with Docker?

Yes, run these two changes at your development environment.

**Comment by hugomd** [comment]
> Yes, run these two changes at your development environment.
I understand that, but I mean is there anything we can set in `package.json` to set no telemetry by default?

**Comment by tim-hub** [comment]
> > Yes, run these two changes at your development environment.
> > I understand that, but I mean is there anything we can set in `package.json` to set no telemetry by default?

no no such config in package.json.

if you go through.

- https://yarnpkg.com/advanced/telemetry
- https://nextjs.org/telemetry

**Pull request merged**
