### PR TITLE
feat: add link to changelog when clicking the version in footer

### PR DESCRIPTION
**Pull request by phiilu**
First of all, thanks for Umami it is great!

The current version is already in the footer, so why not link to the changelog too 😄  
Visually there is only a difference when you hover over it.

### CODE REVIEW

**Review by mikecao — COMMENTED** [review]
The only problem with this is there is not a release for every version number 😞.

**Comment by phiilu** [comment]
I understand 😞 

What about just linking to [https://github.com/mikecao/umami/releases/](https://github.com/mikecao/umami/releases/) so at least we can see where the changelogs might be and can find the nearest version ourselves 🤔

**Comment by mikecao** [comment]
@phiilu Yea I think that's fine

**Comment by phiilu** [comment]
updated the code 👍🏼

**Review by mikecao — APPROVED** [review]
thanks!

**Pull request merged**
